import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
const html = readFileSync(new URL('./index.html', import.meta.url), 'utf8');
const script = readFileSync(new URL('./comparison.js', import.meta.url), 'utf8');
test('switches matching routes, preserves loaded frames, and ignores untrusted route messages', () => {
  const dom = new JSDOM(html, { url: 'http://localhost:3002/', runScripts: 'outside-only' });
  const w = dom.window;
  w.eval(script);
  const current = w.document.getElementById('current-frame');
  const proposed = w.document.getElementById('proposed-frame');
  const message = (origin, source, path) => w.dispatchEvent(new w.MessageEvent('message', { origin, source, data: { type: 'seer:route', path } }));
  message('http://localhost:3000', proposed.contentWindow, '/portfolio?tab=airdrop');
  w.document.getElementById('current').click();
  assert.equal(current.src, 'http://localhost:3001/portfolio?tab=airdrop');
  assert.equal(current.hidden, false);
  assert.equal(proposed.hidden, true);
  const originalWindow = current.contentWindow;
  w.document.getElementById('proposed').click();
  w.document.getElementById('current').click();
  assert.equal(current.contentWindow, originalWindow);
  message('https://evil.example', current.contentWindow, '/wrong');
  message('http://localhost:3001', current.contentWindow, '//evil.example');
  assert.equal(new URL(w.document.getElementById('open').href).pathname, '/portfolio');
  message('http://localhost:3001', current.contentWindow, '/create-market');
  w.document.getElementById('proposed').click();
  assert.equal(proposed.src, 'http://localhost:3000/create-market');
  dom.window.close();
});
